# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
    - state in [ 'present', 'absent' ]

- name: get OS specific variables
  include_vars:
    file: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"

- name: include_tasks for state
  include_tasks: "{{ state }}.yml"

...
