# vim: set ft=yaml ts=2 expandtab:
---

- name: Set up proxy
  hosts: proxy_group

  pre_tasks:

  # https://github.com/geerlingguy/ansible-role-composer/issues/54
  #
  - name: get status of systemd-tmpfiles-setup.service # noqa 303
    command: systemctl status systemd-tmpfiles-setup.service
    when: ansible_service_mgr == 'systemd'
    changed_when: false

  roles:

  - name: mafalb.squid.server


- name: Set up nodes
  hosts: ci

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - name: diff is present
    package:
      name: diffutils

  - name: prepare grub default files
    copy:
      src: "{{ item }}"
      dest: /tmp/{{ item }}
    loop:
    - defaults.cfg
    - defaults-0.cfg
    - defaults-space.cfg
    - defaults-empty.cfg
    - defaults-1.cfg
    - defaults-2.cfg
    - defaults-3.cfg
    - defaults-4.cfg
    - defaults-5.cfg
    - defaults-6.cfg
    - defaults-7.cfg
    - defaults-8.cfg

...
