# vim: set ft=yaml ts=2 expandtab:
---

- name: update grub2 configuration
  command: "{{ grub-mkconfig }} -o {{ grub_config_file }}"
  when:
  - not ansible_virtualization_type in ['lxc','docker','containerd','container']

...
